memory_limit = 1024M
post_max_size = 100M
upload_max_filesize = 100M

# Xdebug 3

xdebug.mode=${PHP_XDEBUG_MODE}
#xdebug.mode=debug,profile,trace
xdebug.start_with_request=${PHP_XDEBUG_START_WITH_REQUEST}
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
#xdebug.remote_port=9003
xdebug.idekey=PHPSTORM
xdebug.connect_timeout_ms=50
xdebug.file_link_format='javascript: var r = new XMLHttpRequest; r.open("get", "http://localhost:63342/api/file/%f:%l");r.send()'


opcache.enable=0
opcache.enable_cli=0

;xdebug.output_dir=/var/log/xdebug-profile/
;xdebug.log=/var/log/xdebug/xdebug.log

#xdebug.discover_client_host = false

#xdebug.log=/var/log/xdebug.log
#xdebug.log_level = 7

# opcache 8.0
#opcache.enable=1
#opcache.enable_cli=1
#opcache.jit_buffer_size=256M
